version: 0.0.{build}
os: Visual Studio 2015
install:
  - ps: Install-Product node $env:nodejs_version x64
  # Sets Windows 7.1 SDK env vars.
  - set "PATH=%ProgramFiles(x86)%\MSBuild\14.0\Bin;%PATH%"
  - npm install -g npm node-gyp
  - set "PATH=%APPDATA%\npm;%PATH%"
  - node -v
  - npm -v
  - call ci/win/exec_with_msys.bat "ci/install.sh" "win"
build: off
artifacts:
  - path: '*.tar.gz'
deploy:
  provider: GitHub
  force_update: true
  auth_token:
    secure: 'eq7/z2ORCaa716+YFUI9iVfelPjD4hU6ITmMEGlYConcRpdnRuX4eoCJizyZzTXv'
  artifact: /.*\.tar\.gz$/
  draft: true
  on:
    branch: arbitrary-release
    appveyor_repo_tag: true
